### ISSUE TITLE
Empty .csv file 

### ISSUE THREAD

**Issue by poiboy** [ale13131/ebay-scraper#1]
**[root@server1 ebay-scraper]# python scraper.py**
```
Traceback (most recent call last):
  File "scraper.py", line 62, in <module>
    bot.searchItem(url,item,ofile)
  File "scraper.py", line 35, in searchItem
    soup = BeautifulSoup(r.content,"lxml")
  File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by ale13131** [comment]
Make sure to add the 'lxml'
pip install lxml
